[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "eda75c636db90909f1f5be2e75ac8dfba87d85ae"
os = "macos"

    [[Qhull.download]]
    sha256 = "d8302ab6476555cb52ff43deee6ae59f01cbcdc8e1bbfdce2d41199228ea5200"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.aarch64-apple-darwin.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "f435abb875d6d2fe7f8ea6fc2f72b4b9be49aeda"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "8bdf26bddd3d8a5fffb89d8acf0a8ef31a6f7ebe4ba5ea0c999879dbef3f5d0b"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "579c55dce9c091bc5d41fe28478c8768c7ad0feb"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "f8a7daf97c3c8460531f02cd52d3b7eb71f4126a7f11ab7792e0655b82fe66ac"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8611532c8bc87a98278d8fc6d4f75ea7983eb22a"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "34bc8271b77aef1760d6cc92fda164ef5d8232229d2fbec769b7dbcf428e0506"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.armv6l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f0ccac4d3f7aec950de46f63031b3386aa4231f"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "0fee180871f5e60910421ece3a1dac689856acaac736a67143f66be2d9a03a2e"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.armv6l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83c759c76b4f809624f0fc7370a2e6ec3c797041"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "20027bb17ee1dc6a3eef01e885bed1d959c0a660fe9d2c4f98ab087d6509d3da"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "265de29902b4b0309817da3b851fc4ff4114fa56"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "dbb48e45b5ed2c4a49a2031f737593af03f625d59d9ab395803971fcce1f8143"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "8084cb2fff8d4c7e948cf499f2b1e7c631609e98"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "75989f987a3e2699c75ac68b049bdbd649af2760c7c7009eb3ad2b8302d3d28d"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "bab613e40f4a59605b5afa1d357725f71476fdb4"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "7ddb4c5d6333323846b1711b2be7323959447defd5171f403021c392c46ea2ee"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "955685ba25ec1e4301424d4b8f8f17b2eda4454d"
os = "windows"

    [[Qhull.download]]
    sha256 = "c3dde9aae332897cad3345f65c222685898953c1ce674788344f58c12ec904ea"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "d625d5cb5944a08e94deeaa5d9b3f6b661c3e34b"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "559e4ca445365d3a3b4b6d039b103f646fafc56adc1b1120315b5c76cb13874c"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "7dca8825bb65b412064aa8ea96bfc9f9369a137a"
os = "macos"

    [[Qhull.download]]
    sha256 = "f488de34373482ea736317fc94c43b317320b5be1846e554ced315654a446cdc"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "d25d83a1ed9a15076c69b0de53fcf0a9b12b5393"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "03a854f3915b497d3525a78972eb5bdeb1ea9233691c75354f50a80510466420"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "dfe81d0dccb68981c3c82f60ba69552577ac69f5"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "9a166a89558a36178747b885cfd185888c3b1623451f4acf7d3baeae58460ac1"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "80fdd7e48e2369f478eb7234d02050e78940213c"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "120a857c6a2dddc63bbe850272f44095ccc020bbd94f8f898258fa8dbe7ebb23"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "92a54657cb75077825f04924f2cb822e9de4149e"
os = "windows"

    [[Qhull.download]]
    sha256 = "335e1c5bd465215cffd664c5a44e112af4e469385a4888d8e606657abcadc803"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1000+0/Qhull.v8.0.1000.x86_64-w64-mingw32.tar.gz"
