[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "02e93ead25b2cc59d0c0a2770d52b3180f51d52d"
os = "macos"

    [[Qhull.download]]
    sha256 = "c4471f8400e227436b69caee5900f9f199c1fe5afc51619225b2dbb49cae766c"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.aarch64-apple-darwin.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "ade7a3b24a8eb277ede96cea2ef70537acdb6667"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "f5cd1e964fd52ec548d8c2a361f4611ec91f9512d069cecfbb2a63674ab79167"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "d65b76acd9ee4fe65a5cb88862089db849292ed6"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "9132973a06fe3f099fa6209d002ccfbe54765f7bba538d5578d1ad63ffb419fc"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1197baaa2e9b9935a9dfc7a80ef6061bad6bf669"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "8f08b26eb130a5519ee6a694987fb1cd67e33add7629e9be990dfe26d18a4e70"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.armv6l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68c9a86d9a3185c02a4dae6da8a25b7f54bceb02"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "bc7bdfa2b6a431b2128bcd6416a940a3c2f1f43abbff30ed28e3f2cd95fb9af0"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.armv6l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da6726764abf4e5790dd5c73bbc8f749501bf06f"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "408e649b712579604ec005f519661c1695bff0e76136ba249dedf18dd909a7c3"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac1a88bb580e0f2142f5d597d44fc860d2bba0b9"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "393a2ff238dccbb00afbff03ccd7d740dd8f78e7aca336b2fd0b752bf4547352"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "4fffa2d83f3edc5d1421293283bd6128d66c8c9c"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "e3c04648ccfb532c38bbdd6c21c01db93e6a7d7a8e71d706a7a48f68ef6d66c9"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "6aebb2cf35b057858065926eea28c21f403f053f"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "e431faffa6632ca8a93f89a6b7213a78e01ef025e345a886114f1fc36530c7e4"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "35c02b8f31f2fcc82273992be51e1793c77e5150"
os = "windows"

    [[Qhull.download]]
    sha256 = "0db424d630d1d0f26b23bfef1fbc3b30e3c6b946bc6bddfbe0df1a972da30421"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "56e50a93a7320b32f7f817a04d99e4f6b370d23f"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "34c1abec4c0b45003604402540f490710456f2fdeaf48ecb72b0cf363dc7c483"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "d6c1a920c794391ae210777b5442e9fdf989ef2d"
os = "macos"

    [[Qhull.download]]
    sha256 = "ec04014059ce0f1f1f84c1941d3664e6c1b77b8275ec69197797a1eb14b5ebfa"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "a0d525546a1895fa7212e5b6cf3229f874282792"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "b346d5058ae3227155fe0fcd08334d63b97e23b81b9e682d1d9682e460a28f14"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "99fb2dbd4ac4b767dda53471078030aaae33ae20"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "2cbe859ba742d4efef001bb255f2dab9bb452c960e4e1f48bc099e2461156e49"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "2a28ee19c9568222ac37b0a5c6c1d2ceae9b9687"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "6e71e2b1b140da1bbbd7b8c8c704ec95cdb0e3bdcecc9aba783dcece398b05bf"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "ec6c64a72eed735d7106cc67d1816f5677156134"
os = "windows"

    [[Qhull.download]]
    sha256 = "49ce48ea9aa3784e1fd0f400d3a3beaa748df8b7ed969daf7a31d8e2f2e35048"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1001+0/Qhull.v8.0.1001.x86_64-w64-mingw32.tar.gz"
