[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "5baa1f67cf0ac5f4bc9b85fcd29ced0f77e2e8b3"
os = "macos"

    [[Qhull.download]]
    sha256 = "c6970c7c8479629f39a400ad11abd5fcf7906ed92a16adefb4f4ca007cec07ae"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.aarch64-apple-darwin.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "a3a3eb18cb34b3ed5163c8233a2f5110b24c4765"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "146ce7391fa21291707dd1f8fb4784c0218875fc41c648e90c9fea2e9a939505"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "f9cd3ad470590d1e96ce91d5e22256a90d3d7856"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "c72a61c875a112c9aac13412c8f7c0955f0d567d2f441a277a49e51967303e0c"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "70c32c52a8f68e64739018189ea57c1f2614b1d9"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "e0c03cd7f585ab32a9b0a1708aa43a6129e715d414fccac28811975b2d70bec9"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.aarch64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b1a94f14d5f7621041f8a867d9d8958f000f91e"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "856b024a1822ed059c990285f3152afd9afcbe3690360257a631a7266dc7f2e7"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.armv6l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4f4aadc27509df444060fa5be4d7241096cac1a"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "191d0c96f5838d509a3093e05d3e5ad8a98d444b7b098df91f361567cb95ac95"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.armv6l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c21f40a0f8a6013d4d007011f0451c22e365b65"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "b3cf88490ca48bac26faeb6d095b191d6b4999f46d50b6ca59d1f43bca3e0eb2"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a58643931909f4d4ef8d7ce84ea593a8026865a7"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "3804f60c995b30ac55af7fb71307f72cbf42ef63e847e171f9c42a7ba77a3624"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "34e6e5676986d7cfeaf8b16a2f32ac1e95171f2e"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "5e731d85505e2aa74927ae4d4fc6242a5e4fb7d6874e0f2a62d7d2be3178dde0"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "ef05bf179a5a6ae69613f65e58a4f97780413e79"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "0b31597b6c392459e9c75826d5b84ed07366ffcefa56a7414a6196b17c3094a3"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "13c6586709fd1b263a78efcd92ee1bd6d0b8bbf9"
os = "windows"

    [[Qhull.download]]
    sha256 = "7772160b5f010fb4eb0316a1183a18e390530e682d6bcf3283b17535c7e4aadc"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "4065de6a8797be5f37423d1081a57092c9c46b6a"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "3abd903cf2752b2e091c6fa870ff79532932c5155d3f6f458543ca67328c556b"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "riscv64"
git-tree-sha1 = "0d728e626115eeb4ffa7978c039893ea4e3a47d4"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "4589f492332ea799c1153253a3b4edfaaf5b03a7171b20897f8b2c2c5cb73141"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.riscv64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "9fd93984c35e73a50502259af008a2945e52e2b7"
os = "macos"

    [[Qhull.download]]
    sha256 = "c56b2932b2838ad0fc04016c66adb67967e7dcfe310440cf69ae980139f369b8"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "0bcce9821f7af4abca0452096d4db3b22628bca4"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "9b617773fa84cb1db5f9b223fb022c90a032f422fb00ade85beb20d765be1e7e"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "acb90be40a3b8bd892fa432bb255ffac6986e0cc"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "152ec3213da7099f9e8a1f2e04f53a29214531f5631c689fd9062ed973e33845"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "33ae7e02007c73caef7cbc3ca758dd0dbebf6e00"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "9d84be4314c089f926be28109f82672253fd615373a0eb711b75db6e7847ba24"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "da11e25c6f132e6233fb5727d966f0e7b88cba16"
os = "windows"

    [[Qhull.download]]
    sha256 = "d68623b3f1c16a107ab7a4b4e0d7680a92a02fe7e045b93c7aa70e65030dd467"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+1/Qhull.v8.0.1003.x86_64-w64-mingw32.tar.gz"
