[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "ebac23a4d8e38bdd6500dc21425b2b02ca4de962"
os = "macos"

    [[Qhull.download]]
    sha256 = "94a1dd84e276339d9deae41e4c4a21d4382a2b5901b1091b7a1e746aed85b333"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.aarch64-apple-darwin.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "1372b1a7b701df580911c6d503616145b2b088d5"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "1a0a3db3464b163ae6f8996f6733f80394938567ce5bf32072ffdaa7f365a38c"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "71a76e4c7895bacb250436a4d77f37967fb25401"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "377752e58caa5462fc2672ba45d714857b7c2c8df585d966f6aebd85ce38ff10"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec03d09abcae06b86c10c69ceae6d2ad16a11d4d"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "51b72c7861d00992d41fd63c06811833fa5b502b36ef58c7d922cae2efa0ebaa"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.armv6l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1ee15ce42409fd0a2a83624209a6db2a1428f7a"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "028b3c38ce76fd9107b209ea794f7d52bdc22081f678717de42d11d1424c67a9"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.armv6l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa98e204a0975dcc487fcafeaafc2dcd3d48e405"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "dda62aa5bd0c11301b7f746247f91fae65697aacd53da1ba7ac9d7df08289766"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "660818b87b231e64c2745c8af1d3920493e7a1c3"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "f9f9f95019494ddf1ce3a3e7a7ac246e6b797f7640bf62808a3faa571fc7f9f3"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "05cc598f82ef8248e2c6b9a16a5e662842758177"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "291f4fae65a5ca37cd726a664257d3713e75fd3a71588a7c30975324910c3e79"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "ebb213ee837dfa77ca5365362d5200ebcef4bd5d"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "550467c8286a53976ac4e0131397db89b8d9a4feb94a285df69a5a0483f55a2d"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "0702796593225bb9baae3bb74052d9645e22c8e6"
os = "windows"

    [[Qhull.download]]
    sha256 = "15a313d0590dcb78fcc02290a459595a0e44d1187a92a6c661b26f08f755d669"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "e99775aad9292bfdfc94471489aba8fe245655a7"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "75578eb8a9e53852fabab874940ae3d8d426af75a54af693ac3d6db622d4bdfb"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "177a9036eab58207687275a999c91fecd9340825"
os = "macos"

    [[Qhull.download]]
    sha256 = "3d6068f2f3087548caaa76539ea13d527872a3a6dee7fb749867ad0182d830ab"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "13b9b9bdb1accb7fc1ac2aa3084dd147982f8f40"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "646e6293b18e5911cf010658cb52cfedd8a74007e6a280dea82eebccd90edbeb"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "4fb930b381524a05a2adf858070c01d67bce8c24"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "42ef06f6b67ab59eb31dceb893f4b8bc81471583359ccc05e349b32d4cef102e"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "27e92240393f8abee2ae2f8afefe92a0682d8181"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "ccdc33149ca49fe4dc76368f3e73976b3130f8614b91df5ea338fa9eb58fd3e6"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "a9f1da02e36476372227c9067f101c4385fc3f38"
os = "windows"

    [[Qhull.download]]
    sha256 = "fd8e539aebf2fb47fc493232bddbc30034329f6b1607a25ff4f9b3a8a362ff6d"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.1003+0/Qhull.v8.0.1003.x86_64-w64-mingw32.tar.gz"
