[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "6ab2c7c1994a8a262a420769ca94592f858b4eef"
os = "macos"

    [[Qhull.download]]
    sha256 = "6f47455df277441bcd97d93c595c591d111374889789b1d53c0997fbba87e8f1"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.aarch64-apple-darwin.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "964d577b54f43a5e614e7b39244667663b096485"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "448a8a51ba8537520463035dc577e9c645393ff5bc1e5284ae6d7f1cccd71efa"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "0648e459a1b614bbfef048e0b3db4f0917b4a1ca"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "f588ed14d683796e4848d113b029cfbf0d503bc26b55dd12a00ae402995742c6"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47404bf7d1228bc4ab9554a45a0a46bbf5151e9a"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "c65d6d02d2f0e35f77107c8d97cfbb98d5d14fbd4c9ff78e773e7940a427b829"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.armv6l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f340a286040eaa30f490590a9161c8cc084293f"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "eef2c226312980104d416e538fc2021c4a4db73a1050cb44f55de3608c233983"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.armv6l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69dd3fa327daddf17ee7a90b8152153fbcb87db0"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "cb02294edcea497c888bdf46f7efd3f2944bb2abdd740fbd53e6cc29f36497da"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e958b14bce6ce4b586f1ff7a6886bfa52d88633a"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "6519c599ba4b56db1e34ac40639f331606d79512f9e565f29d23a1f5d41c1aa0"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "f6c74ec2967fd77d9c51f1eaec08fc624fed0eae"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "9b7e2cc370766101b8b3af1144cb4c52dd8bbc7d0266c34e2261be120a7f4d02"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "83e4d9162c95534892c4a4f570bc841c90b82d60"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "0dcf5acf6a9b9e8f0a9c2a5d0f2c9a10a52fbf39f7d2e2f54d8bea1c57bcb184"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "53e36071dc89b40787bfbe1158f9d04093daac8a"
os = "windows"

    [[Qhull.download]]
    sha256 = "b96acbb39bb1b2bb932977925ede3a5547a2dc82fae36bee75f593ceed21adf5"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "b8db9a30f8429d2c50e1d05e30379e956e8635dd"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "9619f19aa5387d8d7eabc2f290291de43b95a615fcfc6fdbb956c4e8d1f99ead"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "6578ea4709d3dd9f6ea353c31356be807c5dd3c6"
os = "macos"

    [[Qhull.download]]
    sha256 = "601fbabaa501ace94648df328adb21fb4ef6b388f89a7cc18d08491f063ed703"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "79616aed563a579660c5bd4fb576b2ac6d64c475"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "bc7a8b029ccf579df3806190a21562a55869ff2c3d60fbb47ffd1e10e0f6262b"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "7569bd299d66718d1c30864f396af4f0bec5f756"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "782a0e489782e4f080359bffc4a7d15acf27950e5d4fba1c9983d8271fb0c5a4"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "c6ca4666e504ba01bacd37a8fd759d2fae6f3b06"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "755aa80045589dc4f41a93cb61fd0cf81ddac39fa726e1812bf6337d364d2193"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "f44ecdbd50852e7ed6e2a73581ffac37e8a37c1f"
os = "windows"

    [[Qhull.download]]
    sha256 = "6cd0b703a0cff1a99b2d0827f1340e9e018af1d781b97a074eb63c3d88eb4d75"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.999+0/Qhull.v8.0.999.x86_64-w64-mingw32.tar.gz"
