[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "031910ff6f62e1356e4f76a7b220f96a20540763"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "0d8d157b4e3f3a1b010a3731c6bef17c3a6f9bf738bf6db16a75765b622ab540"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.aarch64-linux-gnu.tar.gz"
[[Qhull]]
arch = "aarch64"
git-tree-sha1 = "9cea35daaefaafe22247fc0f633dba1a96dfab4f"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "085ba999ea1a01f93e46109e32f4a773dcd90e1751919460cad510f4a48026d0"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.aarch64-linux-musl.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2476f8f2325f196d40f4491046ccc0b04d60eee6"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "15f2a62076f29337ef1185ecff4461c170153882759ae53be738833b14ed1ed4"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.armv7l-linux-gnueabihf.tar.gz"
[[Qhull]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71d9503281419ea43be8abbae4edb23db69a71f5"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "f963f33822a05a87bb54b5bcc3038a47eb54844cc6778130036509014b6b3a08"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.armv7l-linux-musleabihf.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "2f7b279e72540c4cc5dcce84829ce44a1dbb9ea6"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "7d129c85d6a4d49d7b9bb183e2fe66d3e0fab308b713aa570ddb2cb78266f0e5"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.i686-linux-gnu.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "4e6ceea99552413bc0c9a1861a443dbbed262573"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "67658cf0d194ea4283257b7e2fee89f7b7cd6719528cdf2b1393e593c8f416ab"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.i686-linux-musl.tar.gz"
[[Qhull]]
arch = "i686"
git-tree-sha1 = "3d391b263a13b64a250d769cce79d5c2786312a8"
os = "windows"

    [[Qhull.download]]
    sha256 = "99d704923cc14d8cd469a13c7dedaf8b6a37d47b448846a756250f3f32cd2ddc"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.i686-w64-mingw32.tar.gz"
[[Qhull]]
arch = "powerpc64le"
git-tree-sha1 = "74fd8633d99765df33bc07c07ef431b9cc79dbef"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "f57e6f76577cc308fe490680756138b78514f59a54f051b942cc5543bdce4595"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.powerpc64le-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "c0af224f4fca3a3d6724a5e65f093065172749fc"
os = "macos"

    [[Qhull.download]]
    sha256 = "9235203c9ba0f707d27da2f4766447609e3ccf0dbb37c4211587bc7130fdd940"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.x86_64-apple-darwin.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "00d8d2895a4ba67b00f420eb91fef723121668d2"
libc = "glibc"
os = "linux"

    [[Qhull.download]]
    sha256 = "f241a5276382a71e4a88ad898c958f399285a5ff2b243b9c546ee48c435bca1e"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.x86_64-linux-gnu.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "c377add7fbcee3b677d999f88f6ddab411497dd0"
libc = "musl"
os = "linux"

    [[Qhull.download]]
    sha256 = "d7c41d8a19754c926b2ed80ffce63fc53fea5f1a04d684728b566bfdac1741b6"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.x86_64-linux-musl.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "f2030cb7329ada3f61a2d481f60a24edf3a14ad9"
os = "freebsd"

    [[Qhull.download]]
    sha256 = "fc7614c82937c12b2e7ba583e6f999f14f32bb0f50502587fbf0a5a908a99354"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.x86_64-unknown-freebsd.tar.gz"
[[Qhull]]
arch = "x86_64"
git-tree-sha1 = "662d1f6f8469e186f37d6bf692a6090f3a12dbfa"
os = "windows"

    [[Qhull.download]]
    sha256 = "633098da52438a70f8316ac38cd60e0352433c4cecae674e577114651be34338"
    url = "https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/releases/download/Qhull-v8.0.2+0/Qhull.v8.0.2.x86_64-w64-mingw32.tar.gz"
